server.port=8082
spring.application.name=file-analysis-service

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
spring.jpa.hibernate.ddl-auto=none

eureka.client.enabled=false

logging.level.com.hw3.fileanalysis=INFO
logging.level.org.springframework.web=INFO